// mobile windows
export const MOBILE_WINDOWS_SWITCH_TO_TASK_EDITOR = 'MOBILE_WINDOWS_SWITCH_TO_TASK_EDITOR';
export const MOBILE_WINDOWS_SWITCH_TO_TASK_LIST = 'MOBILE_WINDOWS_SWITCH_TO_TASK_LIST';
export const MOBILE_WINDOWS_SWITCH_TO_SETTINGS = 'MOBILE_WINDOWS_SWITCH_TO_SETTINGS';


// auth - inputs
export const AUTH_CHANGE_INPUT = 'AUTH_CHANGE_INPUT';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILURE = 'AUTH_FAILURE';


// page date button
export const PAGE_DATE_OPEN = 'PAGE_DATE_OPEN';
export const PAGE_DATE_CLOSE = 'PAGE_DATE_CLOSE';


// get data
export const GET_DATA_REQUEST = 'GET_DATA_REQUEST';
export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS';
export const GET_DATA_FAILURE = 'GET_DATA_FAILURE';


// task editor
export const OPEN_TASK_IN_TASK_EDITOR = 'OPEN_TASK_IN_TASK_EDITOR';

export const TASK_EDITOR_INPUT_OPEN = 'TASK_EDITOR_INPUT_OPEN';
export const TASK_EDITOR_INPUT_CLOSE = 'TASK_EDITOR_INPUT_CLOSE';
export const TASK_EDITOR_INPUT_SET = 'TASK_EDITOR_INPUT_SET';
export const TASK_EDITOR_RESET = 'TASK_EDITOR_RESET';

export const TASK_EDITOR_APPLY_START = 'TASK_EDITOR_APPLY_START';
export const TASK_EDITOR_APPLY_SUCCESS = 'TASK_EDITOR_APPLY_SUCCESS';
export const TASK_EDITOR_APPLY_FAILURE = 'TASK_EDITOR_APPLY_FAILURE';

export const TASK_EDITOR_DELETE_START = 'TASK_EDITOR_DELETE_START';
export const TASK_EDITOR_DELETE_SUCCESS = 'TASK_EDITOR_DELETE_SUCCESS';
export const TASK_EDITOR_DELETE_FAILURE = 'TASK_EDITOR_DELETE_FAILURE';


// type editor
export const TYPE_EDITOR_CHANGE_INPUT = 'TYPE_EDITOR_CHANGE_INPUT';

export const OPEN_TYPE_EDITOR = 'OPEN_TYPE_EDITOR';
export const OPEN_TYPE_IN_TYPE_EDITOR = 'OPEN_TYPE_IN_TYPE_EDITOR';
export const TYPE_EDITOR_RESET = 'TYPE_EDITOR_RESET';

export const TYPE_EDITOR_APPLY_START = 'TYPE_EDITOR_APPLY_START';
export const TYPE_EDITOR_APPLY_SUCCESS = 'TYPE_EDITOR_APPLY_SUCCESS';
export const TYPE_EDITOR_APPLY_FAILURE = 'TYPE_EDITOR_APPLY_FAILURE';

export const TYPE_EDITOR_DELETE_START = 'TYPE_EDITOR_DELETE_START';
export const TYPE_EDITOR_DELETE_SUCCESS = 'TYPE_EDITOR_DELETE_SUCCESS';
export const TYPE_EDITOR_DELETE_FAILURE = 'TYPE_EDITOR_DELETE_FAILURE';


// reset states
export const RESET_STATES = 'RESET_STATES';
